apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
      - name: udagram-api-user
        image: emilensengimana/udagram-api-user:v1
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: env-configmap